FROM usgsastro/postgres:9.1

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --force-yes \
        postgis \
        postgresql-9.1-postgis-2.2 \
        postgresql-9.1-postgis-2.2-scripts \
    && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/*


