# vim: ft=dockerfile:

FROM usgsastro/postgres:9.2

RUN apt-get update && apt-get install -y \
        build-essential \
        gdal-bin \
        libgdal-dev \
        libgeos-dev \
        libproj-dev \
        libxml2-dev \
        postgresql-server-dev-9.2 \
    && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/*

ADD http://download.osgeo.org/postgis/source/postgis-2.0.3.tar.gz /tmp/postgis.tar.gz
RUN mkdir /postgis-src && tar xvf /tmp/postgis.tar.gz -C /postgis-src --strip-components 1
WORKDIR /postgis-src
RUN ./configure && make

FROM usgsastro/postgres:9.2

RUN apt-get update && apt-get install -y \
        binutils \
        make \
        libgdal1h \
        libgeos-c1 \
        libproj0 \
        libxml2 \
        postgresql-server-dev-9.2 \
    && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/*

COPY --from=0 /postgis-src /postgis-src
RUN cd /postgis-src && \
    make install && \
    apt-get remove -y postgresql-server-dev-9.2 && \
    cd && \
    rm -rf /postgis-src
