# vim: ft=dockerfile:

FROM postgres:9.1

RUN apt-get update && \
    apt-get install -y ca-certificates curl && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/apt/cache/*
COPY DOIRootCA2.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

RUN curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
